services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: adspy
      POSTGRES_PASSWORD: adspy
      POSTGRES_DB: adspy
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8081:8080"
volumes:
  dbdata:
