[project]
name = "projectscrape"
version = "0.1.0"
dependencies = []

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = ["E","F","I","B","UP","RET","SIM"]
ignore = ["E501"]

[tool.black]
line-length = 100
target-version = ['py311']
